---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.1.10
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi
    after_build:
      - rbenv global 2.1.10
      - gem install bundler --version 1.13.6 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.2.6
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    src: "https://ftp.ruby-lang.org/pub/ruby/2.2/ruby-2.2.6.tar.bz2#e845ba41ea3525aafaa4094212f1eadc57392732232b67b4394a7e0f046dddf7"
    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi
    after_build:
      - rbenv global 2.2.6
      - gem install bundler --version 1.13.6 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.3.2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    src: "https://ftp.ruby-lang.org/pub/ruby/2.3/ruby-2.3.2.tar.bz2#e6ce83d46819c4120c9295ff6b36b90393dd5f6bef3bb117a06d7399c11fc7c0"
    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi
    after_build:
      - rbenv global 2.3.2
      - gem install bundler --version 1.13.6 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.4.0-preview3
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi
      ## Install libssl-dev (OpenSSL 1.1.0 development files) instead of libssl1.0-dev (OpenSSL 1.0.2)
      - apt-get install -y libssl-dev
    after_build:
      - rbenv global 2.4.0-preview3
      ## Check openssl version
      - ruby -ropenssl -ve 'puts OpenSSL::OPENSSL_VERSION'
      - gem install bundler --version 1.13.6 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-jessie:latest
    platform: jessie-amd64
    version: 2.3.2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    src: "https://ftp.ruby-lang.org/pub/ruby/2.3/ruby-2.3.2.tar.bz2#e6ce83d46819c4120c9295ff6b36b90393dd5f6bef3bb117a06d7399c11fc7c0"
    after_build:
      - rbenv global 2.3.2
      - gem install bundler --version 1.13.6 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-wheezy:latest
    platform: wheezy-amd64
    version: 2.3.2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    src: "https://ftp.ruby-lang.org/pub/ruby/2.3/ruby-2.3.2.tar.bz2#e6ce83d46819c4120c9295ff6b36b90393dd5f6bef3bb117a06d7399c11fc7c0"
    after_build:
      - rbenv global 2.3.2
      - gem install bundler --version 1.13.6 -N
      - gem install pry pry-doc pry-coolline -N

