---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.3.7
    src: "https://ftp.ruby-lang.org/pub/tmp/ruby-2.3.7.tar.bz2#18b12fafaf37d5f6c7139c1b445355aec76baa625a40300598a6c8597fc04d8e"
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi
    after_build:
      - rbenv global 2.3.7
      - ruby --version
      - gem --version
      - gem install bundler --version 1.16.1 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.4.4
    src: "https://ftp.ruby-lang.org/pub/tmp/ruby-2.4.4.tar.bz2#45a8de577471b90dc4838c5ef26aeb253a56002896189055a44dc680644243f1"
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi
      ## Install libssl-dev (OpenSSL 1.1.0 development files) instead of libssl1.0-dev (OpenSSL 1.0.2)
      - apt-get install -y libssl-dev
    after_build:
      - rbenv global 2.4.4
      - ruby --version
      - gem --version
      - gem install bundler --version 1.16.1 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.5.1
    src: "https://ftp.ruby-lang.org/pub/tmp/ruby-2.5.1.tar.bz2#4e78d415c7b8c4a4a36bbf6851bdca47c12f8b770cfa38e589c01d3da5f6d4a2"
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi
      ## Install libssl-dev (OpenSSL 1.1.0 development files) instead of libssl1.0-dev (OpenSSL 1.0.2)
      - apt-get install -y libssl-dev
    after_build:
      - rbenv global 2.5.1
      - ruby --version
      - gem --version
      - gem install bundler --version 1.16.1 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.6.0-preview1
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi
      ## Install libssl-dev (OpenSSL 1.1.0 development files) instead of libssl1.0-dev (OpenSSL 1.0.2)
      - apt-get install -y libssl-dev
    after_build:
      - rbenv global 2.6.0-preview1
      - ruby --version
      - gem --version
      - gem install bundler --version 1.16.1 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-stretch:latest
    platform: stretch-amd64
    version: 2.5.1
    src: "https://ftp.ruby-lang.org/pub/tmp/ruby-2.5.1.tar.bz2#4e78d415c7b8c4a4a36bbf6851bdca47c12f8b770cfa38e589c01d3da5f6d4a2"
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.5.1
      - ruby --version
      - gem --version
      - gem install bundler --version 1.16.1 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-jessie:latest
    platform: jessie-amd64
    version: 2.5.1
    src: "https://ftp.ruby-lang.org/pub/tmp/ruby-2.5.1.tar.bz2#4e78d415c7b8c4a4a36bbf6851bdca47c12f8b770cfa38e589c01d3da5f6d4a2"
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.5.1
      - ruby --version
      - gem --version
      - gem install bundler --version 1.16.1 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-wheezy:latest
    platform: wheezy-amd64
    version: 2.5.1
    src: "https://ftp.ruby-lang.org/pub/tmp/ruby-2.5.1.tar.bz2#4e78d415c7b8c4a4a36bbf6851bdca47c12f8b770cfa38e589c01d3da5f6d4a2"
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.5.1
      - ruby --version
      - gem --version
      - gem install bundler --version 1.16.1 -N
      - gem install pry pry-doc pry-coolline -N

