---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.0.0-p647
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    patches:
      - {url: "http://anonscm.debian.org/cgit/collab-maint/ruby.git/patch/?id=d8a4855cd09f42c83526e1391895accbf95a472e", "r51722.diff"}
    after_build:
      - rbenv global 2.0.0-p647
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.1.8
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.1.8
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.2.4
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.4
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.3.0-preview2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.3.0-preview2
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-jessie:latest
    platform: jessie-amd64
    version: 2.2.4
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.4
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-wheezy:latest
    platform: wheezy-amd64
    version: 2.2.4
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.4
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N

