---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.5.0-preview1
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi
      ## Install libssl-dev (OpenSSL 1.1.0 development files) instead of libssl1.0-dev (OpenSSL 1.0.2)
      - apt-get install -y libssl-dev
    after_build:
      - rbenv global 2.5.0-preview1
      - ruby --version
      - gem --version
      - bundle --version
      ## Check openssl version
      - ruby -ropenssl -ve 'puts OpenSSL::OPENSSL_VERSION'
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.5.0-rc1
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi
      ## Install libssl-dev (OpenSSL 1.1.0 development files) instead of libssl1.0-dev (OpenSSL 1.0.2)
      - apt-get install -y libssl-dev
    after_build:
      - rbenv global 2.5.0-rc1
      - ruby --version
      - gem --version
      - bundle --version
      ## Check openssl version
      - ruby -ropenssl -ve 'puts OpenSSL::OPENSSL_VERSION'
      - gem install pry pry-doc pry-coolline -N

