---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.1.10
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    src: "https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.10.tar.bz2#a74675578a9a801ac25eb7152bef3023432d6267f875b198eb9cd6944a5bf4f1"
    after_build:
      - rbenv global 2.1.10
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.2.4
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.4
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.3.0
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.3.0
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-jessie:latest
    platform: jessie-amd64
    version: 2.3.0
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.3.0
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-wheezy:latest
    platform: wheezy-amd64
    version: 2.3.0
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.3.0
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N

