---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.0.0-p645
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.1.6
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.2.2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
  - image: minimum2scp/ruby-jessie:latest
    platform: jessie-amd64
    version: 2.2.2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
  - image: minimum2scp/ruby-wheezy:latest
    platform: wheezy-amd64
    version: 2.2.2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"

