---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.0.0-p647
    src: ftp://ftp.ruby-lang.org/pub/tmp/ruby-2.0.0-p647.tar.bz2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.0.0-p647
      - gem install bundler --version 1.10.5 -N
      - gem install pry -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.1.7
    src: ftp://ftp.ruby-lang.org/pub/tmp/ruby-2.1.7.tar.bz2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.1.7
      - gem install bundler --version 1.10.5 -N
      - gem install pry -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.2.3
    src: ftp://ftp.ruby-lang.org/pub/tmp/ruby-2.2.3.tar.bz2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.3
      - gem install bundler --version 1.10.5 -N
      - gem install pry -N
  - image: minimum2scp/ruby-jessie:latest
    platform: jessie-amd64
    version: 2.2.3
    src: ftp://ftp.ruby-lang.org/pub/tmp/ruby-2.2.3.tar.bz2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.3
      - gem install bundler --version 1.10.5 -N
      - gem install pry -N
  - image: minimum2scp/ruby-wheezy:latest
    platform: wheezy-amd64
    version: 2.2.3
    src: ftp://ftp.ruby-lang.org/pub/tmp/ruby-2.2.3.tar.bz2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.3
      - gem install bundler --version 1.10.5 -N
      - gem install pry -N

