---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.0.0-p645
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.0.0-p645
      - gem install bundler --version 1.9.9 -N
      - gem install pry -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.1.6
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.1.6
      - gem install bundler --version 1.9.9 -N
      - gem install pry -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.2.2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.2
      - gem install bundler --version 1.9.9 -N
      - gem install pry -N
  - image: minimum2scp/ruby-jessie:latest
    platform: jessie-amd64
    version: 2.2.2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.2
      - gem install bundler --version 1.9.9 -N
      - gem install pry -N
  - image: minimum2scp/ruby-wheezy:latest
    platform: wheezy-amd64
    version: 2.2.2
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.2
      - gem install bundler --version 1.9.9 -N
      - gem install pry -N

