---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.1.9
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    src: "https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.9.tar.bz2#4f21376aa11e09b499c3254bbd839e68e053c0d18e28d61c428a32347269036e"
    after_build:
      - rbenv global 2.1.9
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.2.4
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.4
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.3.0
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.3.0
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-jessie:latest
    platform: jessie-amd64
    version: 2.3.0
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.3.0
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-wheezy:latest
    platform: wheezy-amd64
    version: 2.3.0
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.3.0
      - gem install bundler --version 1.11.2 -N
      - gem install pry pry-doc pry-coolline -N

