---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.0.0-p647
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    patches:
      #- {url: "https://github.com/ruby/ruby/commit/801e1fe46d83c856844ba18ae4751478c59af0d1.diff", as: r51722.diff}
      - {file: "r51722_for_2.0.0-p647.diff"}
    after_build:
      - rbenv global 2.0.0-p647
      - gem install bundler --version 1.10.6 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.1.7
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    patches:
      #- {url: "https://github.com/ruby/ruby/commit/801e1fe46d83c856844ba18ae4751478c59af0d1.diff", as: r51722.diff}
      - {file: "r51722_for_2.1.7.diff"}
    after_build:
      - rbenv global 2.1.7
      - gem install bundler --version 1.10.6 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.2.3
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    patches:
      #- {url: "https://github.com/ruby/ruby/commit/801e1fe46d83c856844ba18ae4751478c59af0d1.diff", as: r51722.diff}
      - {file: "r51722_for_2.2.3.diff"}
    after_build:
      - rbenv global 2.2.3
      - gem install bundler --version 1.10.6 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-jessie:latest
    platform: jessie-amd64
    version: 2.2.3
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.3
      - gem install bundler --version 1.10.6 -N
      - gem install pry pry-doc pry-coolline -N
  - image: minimum2scp/ruby-wheezy:latest
    platform: wheezy-amd64
    version: 2.2.3
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    after_build:
      - rbenv global 2.2.3
      - gem install bundler --version 1.10.6 -N
      - gem install pry pry-doc pry-coolline -N

