---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.0.0-p643
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-docs"
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.1.5
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-docs"
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.2.1
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-docs"
  - image: minimum2scp/ruby-wheezy:latest
    platform: wheezy-amd64
    versions: 2.2.1
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-docs"

