---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.3.1
    envs:
      RUBY_CONFIGURE_OPTS: "--disable-install-doc"
    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi
      - DEBIAN_FRONTEND=noninteractive apt-get install usrmerge -y
      - if [ ! -L /bin -a ! -L /lib -a ! -L /sbin ]; then exit 1; fi
      - export -p
      - export PATH=/bin:$PATH
    after_build:
      - rbenv global 2.3.1
      - ruby -rrbconfig -e 'RbConfig::CONFIG.sort_by{|k,v| k}.each{|k,v| p [k,v]}'
      - gem install bundler --version 1.13.6 -N
      - gem install pry pry-doc pry-coolline -N
