---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.6.9

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative --disable-install-doc"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.6.9
      - ruby --version
      - gem --version
      - gem update --system 3.3.3 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.7.5

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.5
      - ruby --version
      - gem --version
      - gem update --system 3.3.3 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 3.0.3

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.3
      - ruby --version
      - gem --version
      - gem update --system 3.3.3 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 3.1.0

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.0
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 2.6.9

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative --disable-install-doc"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.6.9
      - ruby --version
      - gem --version
      - gem update --system 3.3.3 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 2.7.5

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.5
      - ruby --version
      - gem --version
      - gem update --system 3.3.3 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 3.0.3

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.3
      - ruby --version
      - gem --version
      - gem update --system 3.3.3 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 3.1.0

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.0
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 2.6.9

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative --disable-install-doc"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.6.9
      - ruby --version
      - gem --version
      - gem update --system 3.3.3 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 2.7.5

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.5
      - ruby --version
      - gem --version
      - gem update --system 3.3.3 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 3.0.3

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.3
      - ruby --version
      - gem --version
      - gem update --system 3.3.3 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 3.1.0

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.0
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N


