---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.7.7
    openssl:
      version: 1.1.1s
    src: 'https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.7.tar.gz#e10127db691d7ff36402cfe88f418c8d025a3f1eea92044b162dd72f0b8c7b90'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.7
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 3.0.5
    openssl:
      version: 1.1.1s
    src: 'https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.5.tar.gz#9afc6380a027a4fe1ae1a3e2eccb6b497b9c5ac0631c12ca56f9b7beb4848776'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.5
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 3.1.3
    src: 'https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.3.tar.gz#5ea498a35f4cd15875200a52dde42b6eb179e1264e17d78732c3a57cd1c6ab9e'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.3
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 2.7.7
    src: 'https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.7.tar.gz#e10127db691d7ff36402cfe88f418c8d025a3f1eea92044b162dd72f0b8c7b90'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.7
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 3.0.5
    src: 'https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.5.tar.gz#9afc6380a027a4fe1ae1a3e2eccb6b497b9c5ac0631c12ca56f9b7beb4848776'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.5
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 3.1.3
    src: 'https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.3.tar.gz#5ea498a35f4cd15875200a52dde42b6eb179e1264e17d78732c3a57cd1c6ab9e'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.3
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 2.7.7
    src: 'https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.7.tar.gz#e10127db691d7ff36402cfe88f418c8d025a3f1eea92044b162dd72f0b8c7b90'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.7
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 3.0.5
    src: 'https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.5.tar.gz#9afc6380a027a4fe1ae1a3e2eccb6b497b9c5ac0631c12ca56f9b7beb4848776'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.5
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 3.1.3
    src: 'https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.3.tar.gz#5ea498a35f4cd15875200a52dde42b6eb179e1264e17d78732c3a57cd1c6ab9e'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.3
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N


