---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.7.7
    openssl:
      version: 1.1.1s
    install_rust: false

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.7
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 3.0.5
    openssl:
      version: 1.1.1s
    install_rust: false

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.5
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 3.1.3
    install_rust: false

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.3
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 3.2.0
    install_rust: true

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.2.0
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 2.7.7
    install_rust: false

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.7
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 3.0.5
    install_rust: false

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.5
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 3.1.3
    install_rust: false

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.3
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 3.2.0
    install_rust: true

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.2.0
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 2.7.7
    install_rust: false

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.7
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 3.0.5
    install_rust: false

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.5
      - ruby --version
      - gem --version
      - gem update --system 3.3.26 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 3.1.3
    install_rust: false

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.3
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 3.2.0
    install_rust: true

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.2.0
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N


