---
targets:
  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.6.9
    src: 'https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.9.tar.bz2#a0639060c4519572e51828eb742f09dd40f154c820f6007246de7a2090e3ee45'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative --disable-install-doc"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.6.9
      - ruby --version
      - gem --version
      - gem update --system 3.2.32 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 2.7.5
    src: 'https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.5.tar.bz2#d6b444341a5e06fcd6eaf1feb83a1c0c2da4705dbe4f275ee851761b185f4bd1'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.5
      - ruby --version
      - gem --version
      - gem update --system 3.2.32 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 3.0.3
    src: 'https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.3.tar.gz#3586861cb2df56970287f0fd83f274bd92058872d830d15570b36def7f1a92ac'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.3
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby:latest
    platform: sid-amd64
    version: 3.1.0-preview1

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.0-preview1
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 2.6.9
    src: 'https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.9.tar.bz2#a0639060c4519572e51828eb742f09dd40f154c820f6007246de7a2090e3ee45'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative --disable-install-doc"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.6.9
      - ruby --version
      - gem --version
      - gem update --system 3.2.32 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 2.7.5
    src: 'https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.5.tar.bz2#d6b444341a5e06fcd6eaf1feb83a1c0c2da4705dbe4f275ee851761b185f4bd1'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.5
      - ruby --version
      - gem --version
      - gem update --system 3.2.32 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 3.0.3
    src: 'https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.3.tar.gz#3586861cb2df56970287f0fd83f274bd92058872d830d15570b36def7f1a92ac'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.3
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-bullseye:latest
    platform: bullseye-amd64
    version: 3.1.0-preview1

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.0-preview1
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 2.6.9
    src: 'https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.9.tar.bz2#a0639060c4519572e51828eb742f09dd40f154c820f6007246de7a2090e3ee45'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative --disable-install-doc"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.6.9
      - ruby --version
      - gem --version
      - gem update --system 3.2.32 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 2.7.5
    src: 'https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.5.tar.bz2#d6b444341a5e06fcd6eaf1feb83a1c0c2da4705dbe4f275ee851761b185f4bd1'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 2.7.5
      - ruby --version
      - gem --version
      - gem update --system 3.2.32 -N
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 3.0.3
    src: 'https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.3.tar.gz#3586861cb2df56970287f0fd83f274bd92058872d830d15570b36def7f1a92ac'

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.0.3
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N

  - image: minimum2scp/ruby-buster:latest
    platform: buster-amd64
    version: 3.1.0-preview1

    envs:
      RUBY_CONFIGURE_OPTS: "--enable-load-relative"

    before_build:
      ## assert no-merged-usr (see https://github.com/minimum2scp/dockerfiles/pull/191)
      - if [ -L /bin -o -L /lib -o -L /sbin ]; then exit 1; fi

    after_build:
      - rbenv global 3.1.0-preview1
      - ruby --version
      - gem --version
      - gem install bundler --version 1.17.3 -f -N
      - gem install pry pry-doc pry-coolline -N


