version: 2

references:
  build_job: &build_job
    working_directory: /tmp/ruby-binary
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - setup_remote_docker
      - run: docker version
      - run: docker info
      - run: bundle install
      - run: rake build:${target_platform}:prepare
      - run: rake build:${target_platform}:${target_version}
      - run: rake test:${target_platform}:${target_version}
      - run: rm files/binary/.gitkeep files/log/.gitkeep
      - store_artifacts:
          path: files/binary
          destination: binary
      - store_artifacts:
          path: files/log
          destination: log
      - persist_to_workspace:
          root: files/binary
          paths: [ "*.tar.gz" ]

jobs:
  build_sid_2.3:
    <<: *build_job
    environment:
      - target_platform: sid-amd64
      - target_version: 2.3.8
  build_sid_2.4:
    <<: *build_job
    environment:
      - target_platform: sid-amd64
      - target_version: 2.4.5
  build_sid_2.5:
    <<: *build_job
    environment:
      - target_platform: sid-amd64
      - target_version: 2.5.3
  build_sid_2.6:
    <<: *build_job
    environment:
      - target_platform: sid-amd64
      - target_version: 2.6.1
  build_stretch_2.6:
    <<: *build_job
    environment:
      - target_platform: stretch-amd64
      - target_version: 2.6.1
  build_jessie_2.6:
    <<: *build_job
    environment:
      - target_platform: jessie-amd64
      - target_version: 2.6.1
  release:
    working_directory: /tmp/ruby-binary
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - run: curl -o /tmp/ghr.tar.gz -L https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz
      - run: mkdir /tmp/ghr
      - run: tar xf /tmp/ghr.tar.gz -C /tmp/ghr --strip-components=1
      - run: sudo install -m 755 -o root -g root -p /tmp/ghr/ghr /usr/local/bin/ghr
      - run: ghr --version
      - attach_workspace: { at: /tmp/dist }
      - run: ghr -u minimum2scp -r ruby-binary --draft "$(cat VERSION)" /tmp/dist

workflows:
  version: 2
  build_and_release:
    jobs:
      - build_sid_2.3
      - build_sid_2.4
      - build_sid_2.5
      - build_sid_2.6
      - build_stretch_2.6
      - build_jessie_2.6
      - hold:
          type: approval
          filters:
            branches:
              only:
                - master
          requires:
            - build_sid_2.3
            - build_sid_2.4
            - build_sid_2.5
            - build_sid_2.6
            - build_stretch_2.6
            - build_jessie_2.6
      - release:
          requires:
            - hold

