version: 2
jobs:
  build:
    working_directory: /tmp/ruby-binary

    docker:
      - image: circleci/ruby:2.4.1

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Check docker version
          command: |
            set -x
            docker version
            docker info

      - run: rake build:prepare

      - run: rake build:all

      - run: rm files/binary/.gitkeep files/log/.gitkeep

      - store_artifacts:
          path: files/binary
          destination: binary

      - store_artifacts:
          path: files/log
          destination: log

