version: 2

references:
  build_job: &build_job
    working_directory: /tmp/ruby-binary
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout
      - setup_remote_docker
      - run: docker version
      - run: docker info
      - run: rake build:${target_platform}:prepare
      - run: rake build:${target_platform}:${target_version}
      - run: rm files/binary/.gitkeep files/log/.gitkeep
      - store_artifacts:
          path: files/binary
          destination: binary
      - store_artifacts:
          path: files/log
          destination: log
      - persist_to_workspace:
          root: files/binary
          paths: [ "*.tar.gz" ]

jobs:
  2.5.0-preview1:
    <<: *build_job
    environment:
      - target_platform: sid-amd64
      - target_version: 2.5.0-preview1
  2.5.0-rc1:
    <<: *build_job
    environment:
      - target_platform: sid-amd64
      - target_version: 2.5.0-rc1
  bisect:
    working_directory: /tmp/ruby-binary
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout
      - setup_remote_docker
      - run: docker version
      - run: docker info
      - run:
          name: prepare bisect
          command: ./bisect-helper.sh prepare
          working_directory: /tmp/ruby-binary/bisect
      - run:
          name: start bisect
          command: git bisect start v2_5_0_rc1 v2_5_0_preview1
          working_directory: /tmp/ruby-binary/bisect/ruby
      - run:
          name: run bisect
          command: git bisect run ../bisect-helper.sh build
          working_directory: /tmp/ruby-binary/bisect/ruby
      - store_artifacts:
          path: bisect/log
          destination: log

workflows:
  version: 2
  build_and_release:
    jobs:
      - 2.5.0-preview1
      - 2.5.0-rc1
      - bisect

