version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t custom/ruby:2.5.0-rc1 . 2>&1 | tee build-2.5.0-rc1.log
      - store_artifacts:
          path: build-2.5.0-rc1.log
          destination: build-2.5.0-rc1.log

