name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debian_version: [sid, buster, stretch]
        arch: [amd64]
        version: [2.4.9, 2.5.7, 2.6.5, 2.7.0-preview2]
        exclude:
          - { debian_version: buster,  arch: amd64, version: 2.4.9 }
          - { debian_version: buster,  arch: amd64, version: 2.5.7 }
          - { debian_version: buster,  arch: amd64, version: 2.7.0-preview2 }
          - { debian_version: stretch, arch: amd64, version: 2.4.9 }
          - { debian_version: stretch, arch: amd64, version: 2.5.7 }
          - { debian_version: stretch, arch: amd64, version: 2.7.0-preview2 }
      fail-fast: false
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - run: bundle install --jobs=4 --retry=3 --path=vendor/bundle
      - run: rake build:${{ matrix.debian_version }}-${{ matrix.arch }}:prepare
      - run: rake build:${{ matrix.debian_version }}-${{ matrix.arch }}:${{ matrix.version }}
      - run: rake test:${{ matrix.debian_version }}-${{ matrix.arch }}:${{ matrix.version }}
      - run: rm files/binary/.gitkeep files/log/.gitkeep
      - uses: actions/upload-artifact@v1
        with: { name: "binary_${{ matrix.debian_version }}-${{ matrix.arch }}_${{ matrix.version }}", path: files/binary }
      - uses: actions/upload-artifact@v1
        with: { name: "log_${{ matrix.debian_version }}-${{ matrix.arch }}_${{ matrix.version }}", path: files/log }

